#cloud-config

# swap:
#   filename: /swap.img
#   size: auto
#   maxsize: 4294967296

write_files:
  - path: /run/kt-devops-portfolio/playbook.ansible.yaml
    owner: root:root
    permissions: "0644"
    encoding: b64
    content: ${playbook}
  - path: /run/kt-devops-portfolio/playbook.vars.json
    owner: root:root
    permissions: "0644"
    encoding: b64
    content: ${playbook_vars}


runcmd:
  - yum -y update
  - amazon-linux-extras install epel -y
  - yum install ansible -y
  - ansible-playbook -c local -i localhost, --extra-vars @/run/kt-devops-portfolio/playbook.vars.json /run/kt-devops-portfolio/playbook.ansible.yaml
  - rm /var/run/kt-devops-portfolio/playbook.vars.json
