name: CD
on:
  workflow_dispatch:
  
jobs:
  Terraform-Destroy:
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_docker_user: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_docker_pass: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0

      - name: Terraform Init and Apply
        run: |
          cd IAC
          terraform init
          terraform destroy -auto-approve
        env:
          TF_VAR_docker_user: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_docker_pass: ${{ secrets.DOCKERHUB_TOKEN }}